Public Files
arcana-network/storage pull request #129
Opened 2022-09-13 07:23 UTC by mmjee

# Pull Request Template

Resolves [AR-4063](https://team-1624093970686.atlassian.net/browse/AR-4063).

## Blocking dependencies

- [AR-4084](https://team-1624093970686.atlassian.net/browse/AR-4084)

## Changes

See the ticket.

## Checklist

- [x] The branch name follows the format: `developer/AR-XXX-issue-name`.
- [x] The changes have been tested locally.

2022-09-22 04:36 UTC, SauravKanchan reviewed
@mmjee  Can you update usage.MD?

2022-09-22 04:54 UTC, mmjee commented
On 9/22/22 10:06, Saurav Kanchan wrote:
> @SauravKanchan commented on this pull request.
> 
> @mmjee  Can you update usage.MD?
> 
> 
> 
Done.
-- 
Regards,

2022-09-26 09:37 UTC, SauravKanchan requested changes

2022-09-26 09:37 UTC, SauravKanchan commented on src/Uploader.ts
> +              counter: generateCounterFromPartNumber(uploadedParts),
this should be counter

2022-09-26 09:37 UTC, SauravKanchan commented on src/Downloader.ts
> +          const range = `bytes=${i}-${Math.min(i + chunkSize, fileMeta.size)}`;
This should be
```js
const range = `bytes=${i}-${Math.min(i + chunkSize, fileMeta.size)-1}`;
```

2022-09-26 14:58 UTC, merged